### ISSUE TITLE
체크박스 크기 및 마진 조정 필요

### ISSUE THREAD

**Issue by marcusjang** [marcusjang/alcohol-tax-calculator#17]
https://github.com/marcusjang/alcohol-tax-calculator/blob/1989ded6fc2d7f3f88c2dc6469fd9f8c52988bfb/static/stylesheets/style.scss#L450-L456

**문제점**
토글 스위치 미시행시 체크박스의 크기와 마진이 주변 레이아웃을 벗어남

**환경**
MS Edge

**제안**
아래와 같이 수정

```css
input[type=checkbox] {
  display: block;
  height: 1em;
  width: 1em;
}
```
